package org.example.lesson_3

val name: String
val date: LocalDate
var location: String
val budgetDetails: Int
var participantsCount: Int
val duration: Duration
val supplierContacts: List<ContactInfo>
var status: HackathonStatus
val sponsors: List<String>
val budget: Double
var internetAccess: String
val transportInfo: String
var teamCount: Int
val tasks: List<String>
val evacuationPlan: String
var availableEquipment: List<Equipment>
var freeEquipment: List<Equipment>
var mealSchedule: Map<String, String>
val fallbackPlan: String
val judges: List<String>
val feedbackMethods: List<String>
val privacyPolicy: String
val privateFeedback: List<String>
var currentTemperature: Float
var networkPerformance: String
var lightingLevel: Int
var eventLog: MutableList<String>
val medicalSupport: Boolean
val securityPlans: String
val registrationNumber: String
val maxNoiseLevel: Int
var noiseLevelIndicator: Boolean
var eventFormat: EventFormat
var freeSeats: Int
val pressPlan: String
val projectDetails: List<Project>
var permitStatus: Boolean
var exclusiveAccess: Boolean
val partners: List<String>
val eventReport: EventReport by lazy
val prizePlan: String
val emergencyContacts: List<ContactInfo>
val specialConditions: String
var participantMood: String
val hackathonPlan: String
val guestName: String
val maxCapacity: Int
val standardWorkHours: Int